resources:
  - name: depl-mgr-bucket-demo
    type: storage.v1.bucket
    properties:
      location: US
      storageClass: STANDARD
  - name: depl-mgr-vm-demo
    type: compute.v1.instance
    properties:
      zone: us-central1-a
      machineType: zones/us-central1-a/machineTypes/n1-standard-1
      disks:
      - deviceName: boot
        type: PERSISTENT
        boot: true
        autoDelete: true
        initializeParams:
          sourceImage: projects/debian-cloud/global/images/family/debian-9
      networkInterfaces:
      - network: global/networks/default